name: mongodb-geo

replicas: 1

ports:
  - port: 27018
    targetPort: 27017
 
container:
  image: mongo
  imageVersion: 5.0
  name: hotel-reserv-geo-mongo
  ports:
  - containerPort: 27017

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 99
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - geo
        topologyKey: "kubernetes.io/hostname"
