name: memcached-profile

ports:
  - port: 11213
    targetPort: 11211
 
container:
  image: memcached
  imageVersion: 1.6.17
  name: hotel-reserv-profile-mmc
  ports:
  - containerPort: 11211

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 98
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - profile
        topologyKey: "kubernetes.io/hostname"
