name: memcached-reserve

ports:
  - port: 11214
    targetPort: 11211
 
container:
  image: memcached
  imageVersion: 1.6.17
  name: hotel-reserv-reservation-mmc
  ports:
  - containerPort: 11211

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 97
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - reservation
        topologyKey: "kubernetes.io/hostname"
