name: mongodb-rate

replicas: 1

ports:
  - port: 27020
    targetPort: 27017
 
container:
  image: mongo
  imageVersion: 5.0
  name: hotel-reserv-rate-mongo
  ports:
  - containerPort: 27017

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - memcached-rate
        topologyKey: "kubernetes.io/hostname"
