name: memcached-rate

ports:
  - port: 11212
    targetPort: 11211
 
container:
  image: memcached
  imageVersion: 1.6.17
  name: hotel-reserv-rate-mmc
  ports:
  - containerPort: 11211

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rate
        topologyKey: "kubernetes.io/hostname"
