name: search
replicas: 2
ports:
  - port: 8082
    targetPort: 8082
 
container:
  command: ./search
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-search
  ports:
  - containerPort: 8082

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - frontend
        topologyKey: "kubernetes.io/hostname"
