name: profile
replicas: 2
ports:
  - port: 8081
    targetPort: 8081
 
container:
  command: ./profile
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-profile
  ports:
  - containerPort: 8081

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 98
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - frontend
        topologyKey: "kubernetes.io/hostname"
