name: rate

ports:
  - port: 8084
    targetPort: 8084
 
container:
  command: ./rate
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-rate
  ports:
  - containerPort: 8084

configMaps:
  - name: service-config.json
    mountPath: config.json
    value: service-config
affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - search
        topologyKey: "kubernetes.io/hostname"
